export const types = {
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_DRAWER_SUCCEEDED: "TOGGLE_DRAWER_SUCCEEDED",
  TOGGLE_DIALOG: "TOGGLE_DIALOG",
  TOGGLE_DIALOG_SUCCEEDED: "TOGGLE_DIALOG_SUCCEEDED",
};
