export const GRAPH_ACCOUNT_CHECK = 'GRAPG_CHECK_REQUEST';
export const GRAPH_ACCOUNT_EXISTS = 'GRAPH_EXISTS';
export const GRAPH_ACCOUNT_NOT_EXIST = 'GRAPH_NOT_EXIST';
export const GRAPH_FAILURE = 'GRAPH_FAILURE';
